(cl:in-package imu_vn200-msg)
(cl:export '(HEADER-VAL
          HEADER
          ORIENTATION_EULER-VAL
          ORIENTATION_EULER
          GEODETIC_LATITUDE-VAL
          GEODETIC_LATITUDE
          GEODETIC_LONGITUDE-VAL
          GEODETIC_LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          NED_VELOCITIES-VAL
          NED_VELOCITIES
          ATTITUDE_UNCERTAINTY-VAL
          ATTITUDE_UNCERTAINTY
          POSITION_UNCERTAINTY-VAL
          POSITION_UNCERTAINTY
          VELOCITY_UNCERTAINTY-VAL
          VELOCITY_UNCERTAINTY
          ERROR_PRESENT-VAL
          ERROR_PRESENT
          ERROR_STRING-VAL
          ERROR_STRING
))