/* Auto-generated by genmsg_cpp for file /home/ras/igvc_ros/igvc/ros_stacks/igvc_hardware/imu_vn200/msg/EulerOrientation.msg */
#ifndef IMU_VN200_MESSAGE_EULERORIENTATION_H
#define IMU_VN200_MESSAGE_EULERORIENTATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace imu_vn200
{
template <class ContainerAllocator>
struct EulerOrientation_ {
  typedef EulerOrientation_<ContainerAllocator> Type;

  EulerOrientation_()
  : roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  EulerOrientation_(const ContainerAllocator& _alloc)
  : roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;


  typedef boost::shared_ptr< ::imu_vn200::EulerOrientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_vn200::EulerOrientation_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EulerOrientation
typedef  ::imu_vn200::EulerOrientation_<std::allocator<void> > EulerOrientation;

typedef boost::shared_ptr< ::imu_vn200::EulerOrientation> EulerOrientationPtr;
typedef boost::shared_ptr< ::imu_vn200::EulerOrientation const> EulerOrientationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::imu_vn200::EulerOrientation_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::imu_vn200::EulerOrientation_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace imu_vn200

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::imu_vn200::EulerOrientation_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::imu_vn200::EulerOrientation_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::imu_vn200::EulerOrientation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const  ::imu_vn200::EulerOrientation_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_vn200::EulerOrientation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "imu_vn200/EulerOrientation";
  }

  static const char* value(const  ::imu_vn200::EulerOrientation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::imu_vn200::EulerOrientation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
";
  }

  static const char* value(const  ::imu_vn200::EulerOrientation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::imu_vn200::EulerOrientation_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::imu_vn200::EulerOrientation_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EulerOrientation_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_vn200::EulerOrientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::imu_vn200::EulerOrientation_<ContainerAllocator> & v) 
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMU_VN200_MESSAGE_EULERORIENTATION_H

