/* Auto-generated by genmsg_cpp for file /home/ras/igvc_ros/igvc/ros_stacks/igvc_hardware/imu_vn200/msg/vn_200_accel_gyro_compass.msg */
#ifndef IMU_VN200_MESSAGE_VN_200_ACCEL_GYRO_COMPASS_H
#define IMU_VN200_MESSAGE_VN_200_ACCEL_GYRO_COMPASS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"
#include "geometry_msgs/Vector3.h"
#include "geometry_msgs/Vector3.h"

namespace imu_vn200
{
template <class ContainerAllocator>
struct vn_200_accel_gyro_compass_ {
  typedef vn_200_accel_gyro_compass_<ContainerAllocator> Type;

  vn_200_accel_gyro_compass_()
  : header()
  , compass()
  , accelerometer()
  , gyro()
  {
  }

  vn_200_accel_gyro_compass_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , compass(_alloc)
  , accelerometer(_alloc)
  , gyro(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _compass_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  compass;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accelerometer_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  accelerometer;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _gyro_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  gyro;


  typedef boost::shared_ptr< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct vn_200_accel_gyro_compass
typedef  ::imu_vn200::vn_200_accel_gyro_compass_<std::allocator<void> > vn_200_accel_gyro_compass;

typedef boost::shared_ptr< ::imu_vn200::vn_200_accel_gyro_compass> vn_200_accel_gyro_compassPtr;
typedef boost::shared_ptr< ::imu_vn200::vn_200_accel_gyro_compass const> vn_200_accel_gyro_compassConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace imu_vn200

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "07103e522481eee5baba37dd284e0620";
  }

  static const char* value(const  ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x07103e522481eee5ULL;
  static const uint64_t static_value2 = 0xbaba37dd284e0620ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "imu_vn200/vn_200_accel_gyro_compass";
  }

  static const char* value(const  ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
geometry_msgs/Vector3 compass\n\
\n\
geometry_msgs/Vector3 accelerometer\n\
\n\
geometry_msgs/Vector3 gyro\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.compass);
    stream.next(m.accelerometer);
    stream.next(m.gyro);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct vn_200_accel_gyro_compass_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::imu_vn200::vn_200_accel_gyro_compass_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "compass: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.compass);
    s << indent << "accelerometer: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accelerometer);
    s << indent << "gyro: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.gyro);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMU_VN200_MESSAGE_VN_200_ACCEL_GYRO_COMPASS_H

